export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_INFO = 'GET_PRODUCT_INFO';
export const GET_PRODUCT_STYLES = 'GET_PRODUCT_STYLES';
export const GET_RELATED_PRODUCTS = 'GET_RELATED_PRODUCTS';

